version: '2.2'
services:

  db:
    restart: always
    image: postgres:9.6-alpine
    networks:
      db_network:
        ipv4_address: 172.31.0.15
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    volumes:
      - /srv/postgres:/var/lib/postgresql/data
      - ./data_munging_tools/csv_to_SQL.sh:/opt/data_munging_tools/csv_to_SQL.sh
      - ./data_sets/ufo-sightings.csv:/opt/data_munging_tools/ufo-sightings.csv
    command:
      - /opt/data_munging_tools/csv_to_SQL.sh

  flask:
    restart: always
    image: sashanullptr/xcom:latest
    networks:
      external_network:
        ipv4_address: 192.168.1.15
      db_network:
        ipv4_address: 172.31.0.10
    healthcheck:
        test: curl --fail http://localhost:5000/ping || exit 1
        interval: 10s
        timeout: 2s
        retries: 5

networks:
  external_network:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
  db_network:
    internal: true
