version: '2.2'
services:

  db:
    restart: always
    image: postgres:9.6-alpine
    networks:
      - db_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    volumes:
      - /srv/postgres:/var/lib/postgresql/data
      - ./data_munging_tools/csv_to_SQL.sh:/opt/data_munging_tools/csv_to_SQL.sh
      - ./data_sets/ufo-sightings.csv:/opt/data_munging_tools/ufo-sightings.csv
    command:
      - /opt/data_munging_tools/csv_to_SQL.sh

  flask:
    restart: always
    image: sashanullptr/samba:latest
    networks:
      - db_network
    healthcheck:
        test: curl --fail http://localhost:5000/ping || exit 1
        interval: 10s
        timeout: 2s
        retries: 5

networks:
  external_network:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/16
        - subnet: 2600:3c03:e000:027b::/64
  db_network:
    internal: true
